name: CI 2
on:
  workflow_call:
    inputs:
      token-test:
        description: "token value"
        required: true
        type: string
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        env: 
          WHO_TO_TRUST: ${{ secrets.ACTION_TOKEN }}
        if: ${{ inputs.token-test }} ==  env.WHO_TO_TRUST
        run: echo Hello, world!

