name: CI 2
on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
      inputs:
        token-test:
          description: "token value"
          required: true
          type: string

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        env: 
          WHO_TO_TRUST: ${{ secrets.ACTION_TOKEN }}  
        run: echo "${{ github.event.inputs.token-test }}"
        if: ${{ github.event.inputs.token-test }} ==  env.WHO_TO_TRUST

